# default settings for all ci jobs.
default:
  image: azadehafzarhub/gitlab-ci-jekyll-build:latest
  cache:
    paths:
      - vendor/

# job for generating site for master branch for gitlab pages.
main pages:
  stage: deploy
  before_script:
    # setup rbenv.
    - source ~/.bash_profile
    # use ruby version 2.7.0 .
    - rbenv global 2.7.0
    # install dependency gems.
    - bundle config set path 'vendor'
    - bundle install
  script:
    - bundle exec jekyll build --trace -d public
  artifacts:
    paths:
      - public
  only:
    - master

# job for creating preview site for development branch on surge.sh .
development pages:
  stage: deploy
  before_script:
    # setup rbenv.
    - source ~/.bash_profile
    # use ruby version 2.7.0 .
    - rbenv global 2.7.0
    # install dependency gems.
    - bundle config set path 'vendor'
    - bundle install
    # create a CNAME record with desired address for website
    # surge will automatically detect this file at runtime
    - echo "https://azadeh-afzar-kianic-jekyll-theme-development.surge.sh" > CNAME
  script:
    - bundle exec jekyll build --config "_config.yml","_development_config.yml" -d development
    - surge development
  artifacts:
    paths:
      - development
  only:
    - development
