# job for creating preview site for development branch on surge.sh
development:
  stage: build
  image: ubuntu:bionic
  services:
   - ruby:latest
   - node:latest
  cache:
    paths:
      - vendor/
      - node_modules/
  before_script:
    - ruby -v
    - node -v
    - npm -v
    - npm install surge
    - bundle install --path vendor
    - ls -a
  script:
    - bundle exec jekyll build -d development
    - node_modules/.bin/surge development/
  artifacts:
    paths:
      - development
  only:
    - development