image: ruby:2.6

# job for creating preview site for development branch on surge.sh
development:
  stage: build
  cache:
    paths:
      - vendor/
      - node_modules/
  before_script:
    - bundle install --path vendor
    - npm install
  script:
    - bundle exec jekyll build -d development
    - node_modules/.bin/surge development/
  artifacts:
    paths:
      - development
  only:
    - development