# job for creating preview site for development branch on surge.sh
development:
  stage: deploy
  image: ubuntu:bionic
  cache:
    paths:
      - vendor/
      - node_modules/
  before_script:
    # install curl
    - apt-get update -y
    - apt-get install -y curl
    - curl --version
    - command -v curl
    # install gnupg
    - apt-get install -y gnupg
    - gpg --version
    - command -v gpg
    # install ruby version manager (rvm) using curl, then install stable ruby with rvm
    - gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
    - \curl -sSL https://get.rvm.io | bash -s stable --ruby
    - source /usr/local/rvm/scripts/rvm
    - rvm -v
    - command -v rvm
    - ruby -v
    - command -v ruby
    # install node version manager using curl, then install latest node with nvm
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
    - source /root/.bashrc
    - nvm --version
    - command -v nvm
    - nvm install node
    - nvm use node
    - node -v
    - command -v node
    - npm -v
    - command -v npm
    # install ruby and node packages
    - bundle install --path vendor
    - npm install surge
    - ls -a
  script:
    - bundle exec jekyll build -d development
    - node_modules/.bin/surge development/
  artifacts:
    paths:
      - development
  only:
    - development