# job for generating site for master branch for gitlab pages
pages:
  stage: deploy
  image: ruby:latest
  cache:
    paths:
      - vendor/
  before_script:
    - bundle install --path vendor
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  only:
    - master