# --- General Options ---

# Name of website
title: Kianic Jekyll Theme
description: "Multi language, dual theme, stylish, two-column Jekyll theme for your blog."
author: Mahdi Baghbani

# Website domain URL
url: https://azadeh-afzar-kianic-jekyll-theme-development.surge.sh

# Website theme skin
# available skins: default (others coming soon!)
kianic-skin: default

# --- Multi Language Options ---

# number of languages to be supported
language-options:
  lang-number: 2
  lang-default: english
  lang-id:
    - title: english
    - title: farsi

# --- Background and Logo Options ---

# use https://iconifier.net to create all favicon icons and apple touch png
logo-images:
  favicon-png: images/favicon.png
  favicon: images/favicon.ico
  apple-touch-icon: images/apple-touch-icon.png
  apple-touch-icon-57x57: images/apple-touch-icon-57x57.png
  apple-touch-icon-72x72: images/apple-touch-icon-72x72.png
  apple-touch-icon-76x76: images/apple-touch-icon-76x76.png
  apple-touch-icon-114x114: images/apple-touch-icon-114x114.png
  apple-touch-icon-120x120: images/apple-touch-icon-120x120.png
  apple-touch-icon-144x144: images/apple-touch-icon-144x144.png
  apple-touch-icon-152x152: images/apple-touch-icon-152x152.png
  apple-touch-icon-180x180: images/apple-touch-icon-180x180.png
  # site main logo
  # ordered by language
  # recommend: use svg format
  # png size recommendation:
  # - main-homepage 200x200
  # - main-other-pages 50x50
  english:
    logo-main-homepage: images/logo-en.png
    logo-main-other-pages: images/logo-small-en.png
  farsi:
    logo-main-homepage: images/logo-fa.png
    logo-main-other-pages: images/logo-small-fa.png

# Left Block Images
background:
  # this image will be shown on homepage's left block
  homepage: images/Flat-Mountains.svg
  # this image will be shown on post list page
  post-list: images/Rainbow-Vortex.svg
  # this image will be shown when post's front matter doesn't specify any image
  default-post: images/Protruding-Squares.svg

# --- Copyright info ---

# will appear at footer of pages and post
# can be left blank
copyright-license-name: "Creative Commons License BY-NC-SA 4.0"
copyright-license-logo: "images/cc-by-nc-sa.png"
copyright-license-link: "https://creativecommons.org/licenses/by-nc-sa/4.0/"

# --- Jekyll Options ---

# link generation style
permalink:          /:categories/:title/

# markdown compiler
markdown:           kramdown
highlighter:        rouge

# kramdown settings
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false

# specify css path and style
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Custom pages
special-pages:
  resume:        false
  support-me:    true
  about-me:      true
  legal:         true

# --- Social ---

# Social media links
facebook:           MahdiBaghbanii
#instagram:          username
#tumblr:             username
#pinterest:          username
#flickr:             username
twitter:            Baghbani1
#weibo:              username
#goodreads:          userUniquID
linkedin:           MahdiBaghbani
#xing:               username
#youtube:            username
#twitch              username
gitlab:             MahdiBaghbani
github:             MahdiBaghbani
#codepen:            username
#dribbble:           username
#behance:            username
#stackoverflow:      username
#hackernews:         username
#reddit:             username
#quora:              username
#foursquare:         username
#lastfm:             username
#soundcloud:         username
#steam:              username
#fide:               username
#lichess:            username
#chess:              username
#keybase:            username
telegram:           MahdiBaghbanii
#xmpp:               username
protonmail:         MahdiBaghbani@protonmail.com
#email:              username

# select default share links for posts/pages
# you can manually turn this off in each post/page setting
share:
  facebook: true
  twitter: true
  linkedin: true

# --- katex plugin settings ---

katex:
  rendering_options:
    throw_error: true
    error_color: "#cc0000"

# --- Web Trackers ---

# Google Analytics
# using gtag is advised!
# google-analytics: UA-xxxxx-x

# Google Global Site Tag
# google-gtag: UA-xxxxx-x

# Google Tag Manager
# this tag manager job is to track social outbound links
# and contact links such as: mailto:, tel:
# google-gtm: GTM-xxxxxxx

# Heap Analytics
# heap-analytics: xxxxxxxx

# --- Localization Options ---

# you can remove unused ones
# for example if your site is only available in English and German,
# you can remove all other from list below and only keep those two

# if you don't remove, it is still ok!

defaults:
  -
    scope:
      # sub-folder
      path: english
    values:
      # language name, sub-domain and direction (ltr, rtl)
      lang: english
      base-url: "/english/"
      direction-format: ltr
      author: Mahdi baghbani
  -
    scope:
      # sub-folder
      path: farsi
    values:
      # language name, sub-domain and direction (ltr, rtl)
      lang: farsi
      base-url: "/farsi/"
      direction-format: rtl
      author: مهدی باغبانی

# --- Setup Configurations ---

# Ruby Gems
plugins:
  - jemoji
  - jekyll-katex
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

whitelist:
  - jemoji
  - jekyll-katex
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Include list
include: [CNAME, _pages]

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, .gitignore
          LICENSE, Rakefile, .sass-cache, .DS_Store, .idea, CHANGELOG.md]
